### ISSUE TITLE
Tab width in Org files must be 8, not 8.

### ISSUE THREAD

**Issue by rdixitv** [yibie/org-supertag#120]
First of all, I just wanted to say that this package is amazing.

I don't know if this is an issue with org-supertag or not, but I get this warning on startup:

<img width="690" height="63" alt="Image" src="https://github.com/user-attachments/assets/f6085df7-e603-4eee-bfd8-2e580c19296a" />

It seems to be related to bulleted lists. Whenever I save a file with one, the warning appears. If I uninstall org-supertag, I no longer have the warning.

The actual package functions fine, but this warning keeps popping up. I haven't changed my default tab width in my config. I've also tried this, but it doesn't fix the issue:

```elisp
(add-hook 'org-mode-hook
           (lambda ()
             (setq-local tab-width 8)))
```

The same warning was discussed in on the [Doom Emacs issue tracker (#7670)](https://github.com/doomemacs/doomemacs/issues/7670), but none of the solutions there worked for me.

I am using Doom Emacs on Emacs 30.2 on macOS 26.0

This is my `M-x doom/info` if needed: https://pastebin.com/AM3R83rm

Thank you for your time.

**Comment by yibie** [comment]
I'm confused, the `tab-width` value hasn't been set in any file in `org-supertag`.

**Comment by yibie** [comment]
Please update to lastest version, and tell me the warning message would show up or not.

**Comment by rdixitv** [comment]
I have updated to the latest version, and the warning still persists. It may not be directly related to this package. The warning message doesn't really make sense either.

**Comment by garyo** [comment]
I'm sure you know this, but you can set a breakpoint in that error message (line 1243 of org-macs.el for me, in the macro org-current-text-column) and get a debugger trace to help you figure it out. Looking at that macro, I think the error is buggy anyway, because it resets tab-width first, before printing the error.

**Comment by yibie** [comment]
Hi, @rdixit @garyo I'm not sure if the issue occurs during the handling of temporary buffers, because org-supertag currently copies the text content to a temporary buffer for processing before saving the data, to avoid interfering with the current buffer. I have now forcefully applied the (tab-width 8) setting to the temporary buffer.

Please update to the latest version and check if the waning message still appears.

**Comment by rdixitv** [comment]
The update seems to have fixed that issue. I'm no longer getting that particular warning.

However, I am getting a different warning now on startup:
`⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer  *temp*> (fundamental-mode)`

This time, it is only on startup and not whenever I write to a file.

**Comment by yibie** [comment]
Ok, this issue is more easy to fix. Later.

**Comment by yibie** [comment]
@rdixitv Update to the lastest version.

**Comment by yibie** [comment]
Done.

**Comment by yibie** [comment]
Yes, please update.

**Comment by rdixitv** [comment]
Sorry, but the warning is still appearing. I am not too experienced with Emacs, so would you recommend any way to troubleshoot this myself to see where the problem may be stemming from?

**Comment by yibie** [comment]
`The issue doesn't happen when I use emacs -Q -l test.el and load org-supertag along with my org config `

I think this issue occurs elsewhere, because loading org-supertag in a pure environment does not cause this warning message to appear. 

I suspect it's caused by another plugin. You can try loading the packages related to `org-mode` one by one using `emacs -Q` to see which one is causing the issue.
